osx_image: xcode9.2
language: objective-c
cache:
  - bundler
  - cocoapods
branches:
  only:
    - develop
    - master
notifications:
  email: false
before_install:
  - gem install bundler
  - brew update
#  - bundle install && brew bundle
#install: bundle exec pod install --repo-update --silent
script: bundle exec fastlane hoverview_main